### ISSUE TITLE
Create a navigation bar

### ISSUE THREAD

**Issue by Thomas-Tomo** [Thomas-Tomo/devexchange#21]
### User Story

As a **user**,
I want to **view the navigation bar from every page**,
So that **I can navigate easily between pages**.

### Acceptable Criteria

1. Sign In
2. Sign Out
3. All links work as expected

### Tasks
- [x] Create a navigation bar that allows user sign in/sign out
- [x] Style navigation bar
- [x] Add font awesome icons for links to make it user friendly
