### ISSUE TITLE
View all most recent posts

### ISSUE THREAD

**Issue by Thomas-Tomo** [Thomas-Tomo/devexchange#27]
### User Story

As a **user**,
I want to **see all the most recent posts**,
So that **I can stay up to date with newest content**.

### Acceptable Criteria

1. View recent  posts
2. Search posts
3. Infinite scroll

### Tasks
- [x] Display all posts
- [x] Create a search bar
- [x] Create infinite scroll funtionality
