### ISSUE TITLE
Profile header

### ISSUE THREAD

**Issue by Thomas-Tomo** [Thomas-Tomo/devexchange#33]
### User Story

As a **user**,
I want to **see users profiles, or edit my own**,
So that **I can see how many followers or posts they have, or how many I have**.

### Acceptable Criteria

1. Display post, job post, followers, following counts
2. Edit form to edit profile

### Tasks
- [x] Render job posts count for employer accounts only
- [x] Add an edit profile form
- [x] Customize Edit forms to match the site design
