### ISSUE TITLE
Job Posts

### ISSUE THREAD

**Issue by Thomas-Tomo** [Thomas-Tomo/devexchange#35]
### User Story

As a **user**,
I want to **if I am an employer I want to create job posts**,
So that **I can add jobs so other users could see it and possibly apply for it**.

### Acceptable Criteria

1. Users can see, like, comment and reply on the job post
2. Only employer accounts can create job posts
3. Add a save button to add job posts under saved page

### Tasks
- [x] Create Job Post form
- [x] Create Job Post component
- [x] Set up permissions for employer accounts
- [x] Users can save a job post
