### ISSUE TITLE
Company Bio

### ISSUE THREAD

**Issue by Thomas-Tomo** [Thomas-Tomo/devexchange#37]
### User Story

As an **employer user**,
I want to **be able to add my company details on my profile page**,
So that **other users could see it and possibly reach out incase they are interested in employment**.

### Acceptable Criteria

1. Only employer accounts can create company bio
2. All users can see the company bio displayed on employer profiles
3. Owner of the profile can edit or delete their company bio details

### Tasks
- [x] Create a company bio create form
- [x] Create a company bio edit form
- [x] Set up permissions for employer accounts
